### ISSUE TITLE
OS X doesn't build yet

### ISSUE THREAD

**Issue by schmonz** [DerDakon/Qsmtp#1]
I'm working on getting Qsmtp 0.35 added to pkgsrc, and ran into at least these compile errors on Mac OS X (10.14.5 "Mojave"):

- No `<bits/wordsize.h>`, not sure what's equivalent (referenced in `include/fmt.h`)
- `s6_addr32` doesn't exist, but `__u6_addr.__u6_addr32` does (many files; I've had good luck across pkgsrc platforms with [these macros](https://github.com/schmonz/pkgsrc-qmail-spp-spf/blob/master/patches/patch-qmail-spp-spf-20091020.c#L32-L38))
- `s6_addr16` doesn't exist either; maybe `__u6_addr.__u6_addr16` is how to say it on OS X? (`tools/qsurvey.c`)
- `O_DIRECTORY` is defined in `<sys/fcntl.h>` but protected by `#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)` (`diropen.h` and some tests)

I'd be happy to give it another go once these are fixed.

**Comment by DerDakon** [comment]
Please try out the macos branch, it should hopefully fix all but the first issue. The CMake test in the latter commit seems broken, but since it fails it will just set the defines.

**Comment by schmonz** [comment]
```
Scanning dependencies of target qsmtp_lib
[  0%] Building C object lib/CMakeFiles/qsmtp_lib.dir/control.c.o
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/lib/control.c:119:6: warning: implicit declaration of function 'flock' is
      invalid in C99 [-Wimplicit-function-declaration]
        if (flock(fd, LOCK_SH | LOCK_NB) != 0) {
            ^
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/lib/control.c:119:16: error: use of undeclared identifier 'LOCK_SH'
        if (flock(fd, LOCK_SH | LOCK_NB) != 0) {
                      ^
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/lib/control.c:119:26: error: use of undeclared identifier 'LOCK_NB'
        if (flock(fd, LOCK_SH | LOCK_NB) != 0) {
                                ^
```

**Comment by DerDakon** [comment]
So it seems requesting a posix level restricts everything to that API and hides all extensions. If you skip the first commit, what is the actual error about O_DIRECTORY? Could you try in a clean build directory and look in the CMake log files after only running cmake, not make, what the results of the O_DIRECTORY CMake test have been?

**Comment by schmonz** [comment]
Skipping the first commit, the compile error is:
```
[ 39%] Building C object tests/CMakeFiles/testcase_cmd_rcpt.dir/__/qsmtpd/commands.c.o
In file included from /Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/qsmtpd/commands.c:3:
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/include/diropen.h:45:40: error:
      use of undeclared identifier 'O_DIRECTORY'
        fd = openat(base, dirname, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
```

In the same tree, after `cmake` but before `make`, looks like it found `O_DIRECTORY`:
```
CMakeCache.txt
555://Have symbol O_DIRECTORY
556:HAS_O_DIRECTORY:INTERNAL=1
```

**Comment by DerDakon** [comment]
Please test the current master and macos branches and report back.

**Comment by schmonz** [comment]
On macOS Catalina 10.15.2, with Qsmtp on the `macos` branch at commit `7304f2e`:

```
Scanning dependencies of target testcase_qsdata
[ 47%] Building C object tests/CMakeFiles/testcase_qsdata.dir/qsdata_test.c.o
In file included from /Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/tests/qsdata_test.c:5:
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/tests/../qsmtpd/data.c:625:2: warning:
      FIXME: loop detection missing [-W#warnings]
#warning FIXME: loop detection missing
 ^
/Users/schmonz/Documents/trees/pkgsrc-current/mail/qsmtp/work.magnetic-babysitter/tests/qsdata_test.c:54:1: error:
      conflicting types for 'gettimeofday'
gettimeofday(struct timeval *tv, struct timezone *tz)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/time.h:197:9: note:
      previous declaration is here
int     gettimeofday(struct timeval * __restrict, void * __restrict);
        ^
1 warning and 1 error generated.
*** Error code 1

Stop.
```

**Comment by schmonz** [comment]
macOS build sure seems fixed. If I find any runtime or other build issues I'll file them separately. Thanks!
